### ISSUE TITLE
opticks-externals-install fails

### ISSUE THREAD

**Issue by ggalgoczi** [BNLNPPS/esi-shell#117]
opticks-externals-install fails with 

CMake Error at CMakeLists.txt:206 (message):
  RandR headers not found; install libxrandr development package

-----------------------------------------------------------------------------------------------------

However if I run:

opticks-full-prepare
opticks-externals-install

I get

############## glm ###############

'glm' -> 'glm-0.9.9.5/glm'
=== glm-get : planting symbolic link for access without version in path

############## glfw ###############

gmake: Makefile: No such file or directory
gmake: *** No rule to make target 'Makefile'.  Stop.
=== glfw-- : make/instal FAIL
=== opticks-installer- : RC 3 from pkg glfw : ABORTING

**Comment by ggalgoczi** [comment]
Solved by entering cd /usr/local/opticks/externals/glfw/glfw-3.3.2.build/ and running cmake, gmake by hand.

Then had other errors but running the install [script](https://github.com/hanswenzel/CaTS/blob/main/scripts/checkpr.sh) written by CaTS devs solved the errors and the install ran successfully from within the shell.

**Comment by plexoos** [comment]
In `esi-shell` we don't install external dependencies via `opticks-externals-install` command. The `glm` package is installed by Spack and can be found by any cmake script using the standard `find_package` command. You can check all installed packages with `spack find` or `spack find -p glm` if you need its specific location.

The `/usr/local/opticks/externals/` directory does not exist in the container and it is not needed to compile Opticks.

**Comment by ggalgoczi** [comment]
You suggested to build CaTS within the shell. For CaTS opticks-externals-install is required per documentation.

**Comment by ggalgoczi** [comment]
Thanks for the info, I will check how that works anyway!

**Comment by plexoos** [comment]
Sure. There are different ways to reach the same goal. The CaTS developers are not aware of the changes we have in our fork [bnlnpps/esi-opticks](https://github.com/bnlnpps/esi-opticks)
