### ISSUE TITLE
Install self-hosted runner on npps0 for GPU based CI jobs

### ISSUE THREAD

**Issue by plexoos** [BNLNPPS/esi-shell#38]

**Comment by plexoos** [comment]
> One self-hosted runner can only run one job at a time, when no available runners are idle, the subsequent jobs will be in queueing until available runners are idle.

but it should be possible to setup multiple self-hosted runners on the same node...?

**Comment by buddhasystem** [comment]
I think it's token-based, right? So it should be possible...

**Comment by plexoos** [comment]
Installing and starting runners in separate directories (same host) might work... I saw this suggested somewhere but haven't tried yet
